### ISSUE TITLE
berks.bat failed with return code: 100

### ISSUE THREAD

**Issue by sngehl01** [chef-partners/vsts-chef#23]
I have had a lot of issues with the "Upload Cookbook to Chef Server" task. I am able to successfully update the cookbook version # in the environment, but I cannot upload the cookbook. I get the following error in VSTS : 
- CD to cookbook directory: d:\_work\r1\a/_demo
- [command]C:\Windows\system32\cmd.exe /D /S /C "c:\opscode\chefdk\bin\berks.bat install"
- No Berksfile or Berksfile.lock found at 'd:/_work/r1/a/_demo'!
- ##[error]c:\opscode\chefdk\bin\berks.bat failed with return code: 100

Googling error codes hasn't gotten me far. I get the same error when I try to remote into the machine and run the berks.bat install command (No Berksfile of Berksfile.lock found at 'C:/opscode/chefdk/bin'!)

I do have the berkshelf gem here : C:\opscode\chefdk\embedded\lib\ruby\gems\2.5.0\gems\berkshelf-7.0.4

I installed chefdk 3.1.0

Any ideas? thanks.

**Comment by stuartpreston** [comment]
If you can't run `berks install` on the machine from the specified folder, then it's definitely not going to work in the VSTS task :)  Are you sure the **_demo** folder is actually a Chef cookbook (usually contains a metadata.rb file as well as a Berksfile identifying the source for dependencies)?

**Comment by stuartpreston** [comment]
I forgot to mention - did you try setting **System.Debug** to **true** in case any more output is returned?

**Comment by sngehl01** [comment]
You're a gentleman and a scholar :) I will say my _demo folder was right... and wrong, haha. There's a drop folder in it. The cookbook is in _demo/drop. I did change that. I got a new error.

**Comment by sngehl01** [comment]
Sorry, didn't mean to comment yet. 
2018-08-21T15:47:57.4610080Z ##[error]c:\opscode\chefdk\bin\berks.bat failed with return code: 130

It looks like it can't read the pem. It doesn't show up in the folder it's looking for. I grabbed it during the deployment and the RSA key looks ok (or as I'd expect it to look). 

More complete error text : 

- [command]C:\Windows\system32\cmd.exe /D /S /C "c:\opscode\chefdk\bin\berks.bat upload -c c:\windows\temp\berks.config.json"
- [2018-08-21T11:47:57-04:00] WARN: Failed to read the private key c:windows	empsts-task.pem: #<Errno::EINVAL: Invalid argument @ rb_sysopen - c:windows	empsts-task.pem>
-  E, [2018-08-21T11:47:57.426060 #1508] ERROR -- : Chef::Exceptions::PrivateKeyMissing: I cannot read c:windows	empsts-task.pem, which you told me to use to sign requests!
-  E, [2018-08-21T11:47:57.426486 #1508] ERROR -- : c:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0-universal-mingw32/lib/chef/http/authenticator.rb:98:in `rescue in load_signing_key'
- c:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0-universal-mingw32/lib/chef/http/authenticator.rb:84:in `load_signing_key'

No on the System.Debug to true, where would I set that?

**Comment by stuartpreston** [comment]
@sngehl01 Looks like I missed this reply - did you get past this issue?
